name = "gbr_shared"
version = "1.0.2-alpha"

description = "Shared libraries to target javascript and erlang by @gleam-br."
repository = { type = "github", user = "gleam-br", repo = "gbr_shared" }
licences = ["Apache-2.0"]
links = []

[dependencies]
tom = "~> 1.0"
gleam_stdlib = "~> 0.69"
gleam_json = "~> 3.1"
gleam_http = "~> 4.3"

[dev-dependencies]
gleeunit = "~> 1.9"
